# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ZEMSpace
tagline:          'Nice to meet you.'
description:      'ZEMSpace a personal space for ZEM syed to potray to the world his unique ideas and thoughts.'
url:              zaheensyed.github.io/
baseurl:          /

author:
  name:           'Zaheen Syed'
  url:            zaheensyed.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           zaheensyed/zaheensyed.github.io
